CREATE DATABASE IF NOT EXISTS svfuture_demo;
USE svfuture_demo;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  balance DOUBLE DEFAULT 1000,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS trades (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  type ENUM('buy', 'sell') NOT NULL,
  symbol VARCHAR(20) NOT NULL,
  amount DOUBLE NOT NULL,
  price DOUBLE NOT NULL,
  leverage INT DEFAULT 1,
  margin DOUBLE DEFAULT 0,
  pnl DOUBLE DEFAULT 0,
  closed TINYINT DEFAULT 0,
  closedAt TIMESTAMP NULL DEFAULT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id)
);
